# Generated by Django 4.1.7 on 2023-03-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_categories_name_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name_categories',
            field=models.CharField(max_length=20),
        ),
    ]
